### ISSUE TITLE
Reproduce the results shown by Two-step Methods in baslines

### ISSUE THREAD

**Issue by jweihe** [Niuchx/HimNet#1]
Hello, this is a very good work! Can you tell me how to reproduce the results shown by Two-step Methods in baslines, is there a code I can refer to?

**Comment by Niuchx** [comment]
Hello, you can refer to https://github.com/yli96/iForest and https://github.com/LingxiaoShawn/GLOD-Issues/tree/main for the implementation of the two-step anomaly detection methods.
